### ISSUE TITLE
script run succeed but not updated

### ISSUE THREAD

**Issue by 4ft35t** [MuntashirAkon/chrome_os_updater#1]
I had installed with Option 1 of
https://github.com/imperador/chromefy 

The installed version is `eve-release/R74-11895.118.0`
The script download `chromeos_12499.66.0_eve_recovery_stable-channel_mp-v2.bin`
After the script print `Update complete. You can now reboot safely.` 
reboot

the version is still `74.0.3729.159`

**Comment by 4ft35t** [comment]
I find out the reason
My PC boot with BIOS, this script just modify UEFI.
Switch to boot with UEFI, everything is fine.

**Comment by MuntashirAkon** [comment]
I'll add it as a note.

**Comment by MuntashirAkon** [comment]
> I find out the reason
> My PC boot with BIOS, this script just modify UEFI.
> Switch to boot with UEFI, everything is fine.

The new script (not yet released) supports both EFI and legacy boot mode. Hopefully, lagacy users can also update their Chrome OS.
