### ISSUE TITLE
The script doesn't really work now

### ISSUE THREAD

**Issue by PiktCai** [MuntashirAkon/chrome_os_updater#10]
Thanks to @MuntashirAkon first.
According to the commits, I realized you optimized this project very much in these days. But it seems that the Usage part of readme.md doesn't work now. I inputed sudo `sudo -E omaha_cros_update.sh `, but it showed me
`Initializing parameters for this update attempt
Download channel for this attempt = beta-channel
Running from channel stable-channel
`
and then nothing happened.

I tried to click the buttom in About Chrome OS page, but after 100% it told me that my OS had already updated to the newest version. So I rebooted, but it showed me a black screen, so I had to turn back. Please give me some solution.

**Comment by MuntashirAkon** [comment]
> it seems that the Usage part of readme.md doesn't work now.

As I've mentioned at the top of readme, the master branch is unstable. Use v2.2.0 from the release section.

**Comment by PiktCai** [comment]
> > it seems that the Usage part of readme.md doesn't work now.
> 
> As I've mentioned at the top of readme, the master branch is unstable. Use v2.2.0 from the release section.

Sorry, it's my fault. I will try that.
