### ISSUE TITLE
Curl Problem

### ISSUE THREAD

**Issue by volram** [MuntashirAkon/chrome_os_updater#13]
![Screenshot 2020-08-22 at 01 55 21](https://user-images.githubusercontent.com/13249913/90968583-21cc9500-e4c4-11ea-8bc6-b9a82da90f33.png)

**Comment by MuntashirAkon** [comment]
This is probably a problem with [chromebrew](https://github.com/skycocker/chromebrew). If you have just tried this command one time, I suggest you try another and create an issue in the linked repository. I also suggest you to try this command instead of that short one:
```
curl -Ls https://github.com/MuntashirAkon/chrome_os_updater/releases/latest/download/installer.sh | bash
```

**Comment by volram** [comment]
Nope. It is with the curl library. When I run the command curl -v, I get the message: curl: symbol lookup error: /usr/lib64/libcurl.so.4: undefined symbol: SSL_COMP_free_compression_methods.

**Comment by MuntashirAkon** [comment]
> Nope. It is with the curl library. When I run the command curl -v, I get the message: curl: symbol lookup error: /usr/lib64/libcurl.so.4: undefined symbol: SSL_COMP_free_compression_methods.

Yes, I can see that, of course. However, it did download the first two dependencies of chromebrew and failed for ruby. So, my guess is this is something to do with how ruby is being downloaded. The script that downloads chromebrew dependencies is located in their repository. Therefore, I cannot do anything about it.

PS: There's a closed issue is their repo regarding this: https://github.com/skycocker/chromebrew/issues/4202

**Comment by volram** [comment]
export LD_LIBRARY_PATH=' '
Did the trick for me. Thanks for pointing to the post (https://github.com/skycocker/chromebrew/issues/4202).
