### ISSUE TITLE
Specify a download location

### ISSUE THREAD

**Issue by Semen8991** [MuntashirAkon/chrome_os_updater#8]
Hello!  I have a 16 GB drive, 4 and 4 are used for ROOT-A and ROOT-B.  After downloading the update, the script throws an error that there is not enough space for unzipping.  How can I download to an SD card or run a script from it?

**Comment by buhlaze** [comment]
yeah, i have the same issue

**Comment by MuntashirAkon** [comment]
Fixed via ea0b463838a43fde0983a7d4fb7963f8e40a54b4
